name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.8

  # Networking & API
  http: ^1.2.0
  socket_io_client: ^2.0.3 # For real-time chat

  # Storage & State
  shared_preferences: ^2.2.2 # To store login token
  provider: ^6.1.1 

  # UI Utilities
  image_picker: ^1.0.7  # To select photos
  intl: ^0.19.0         # Date formatting
  cached_network_image: ^3.3.1 # Smooth image loading
  timeago: ^3.6.1       # "5 mins ago" format

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true